M48
; DRILL file {KiCad 8.0.2-1} date 2024-06-13T15:22:44+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-13T15:22:44+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.889
%
G90
G05
T1
X136.785Y-94.26
X142.565Y-94.26
T2
X140.4Y-109.4
X143.397Y-109.4
M30
