M48
; DRILL file {KiCad 8.0.2-1} date 2024-05-30T11:00:18+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-30T11:00:18+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.889
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.500
%
G90
G05
T1
X136.785Y-94.26
X142.565Y-94.26
T2
X140.4Y-109.4
X143.397Y-109.4
T3
X133.5Y-89.5
X133.5Y-110.5
X166.5Y-89.5
X166.5Y-110.5
M30
